server {
	listen 8080;
	root ./www;
	index index.html;
	client_max_body_size 2k;

	error_page 403 ./www/error_pages/403.html;
	error_page 404 ./www/error_pages/404.html;
	error_page 405 ./www/error_pages/405.html;
	error_page 413 ./www/error_pages/413.html;
	error_page 500 ./www/error_pages/500.html;

	location / {
		allow_methods GET POST DELETE;
		autoindex off;
	}

	location /uploads {
		allow_methods GET POST DELETE;
		autoindex on;
		upload_path ./www/uploads;
	}

	location /readonly {
		allow_methods GET;
		autoindex on;
	}

	location /redirect {
		return 302 /;
	}

	location /cgi-bin {
		allow_methods GET POST;
		autoindex off;

		cgi .py /usr/bin/python3;
		cgi .php /usr/bin/php-cgi;
	}
}

server {
	listen 8081;
	root ./www/listener;
	index index.html;
	client_max_body_size 2k;

	location / {
		allow_methods GET POST DELETE;
		autoindex off;
	}
}
